In [12]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

In [13]:
digits=load_digits()

In [14]:
x=digits.data
y=digits.target

In [15]:
x_std = StandardScaler().fit_transform(x)

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=2)

In [17]:
pca=PCA(n_components=2)

In [18]:
x_new=pca.fit_transform(x)
x_new

array([[ -1.25946547,  21.27487814],
       [  7.95760859, -20.76869985],
       [  6.99192399,  -9.95598036],
       ...,
       [ 10.80128744,  -6.96025793],
       [ -4.87209163,  12.42393777],
       [ -0.34438617,   6.36554833]])

In [19]:
reg = LogisticRegression()

In [21]:
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
pred = reg.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score

In [28]:
print(accuracy_score(pred, y_test))

0.9361111111111111


In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
print(confusion_matrix(pred, y_test))

[[32  0  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  2  0  0  0  2  0]
 [ 0  0 31  0  0  0  0  0  0  0]
 [ 0  1  0 31  0  0  0  0  0  1]
 [ 0  0  0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0 43  0  0  0  1]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  3  0  0  0 39  0  1]
 [ 0  1  0  2  1  0  1  1 33  3]
 [ 0  1  0  0  1  0  0  0  1 22]]


In [31]:
from sklearn.metrics import classification_report

In [32]:
print(classification_report(pred, y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        32
          1       0.93      0.91      0.92        45
          2       1.00      1.00      1.00        31
          3       0.86      0.94      0.90        33
          4       0.89      1.00      0.94        31
          5       1.00      0.98      0.99        44
          6       0.97      1.00      0.99        34
          7       0.97      0.91      0.94        43
          8       0.92      0.79      0.85        42
          9       0.79      0.88      0.83        25

avg / total       0.94      0.94      0.94       360

