In [82]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn import preprocessing 
%matplotlib inline

In [83]:

from sklearn.datasets import load_digits

In [84]:
digit = load_digits()
x=digit.data
y=digit.target

In [86]:
x=pd.DataFrame(x)
y=pd.DataFrame(y)

In [88]:
x.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
reg =  LogisticRegression()

In [11]:
reg.fit(x_train,y_train)

C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
reg.coef_

array([[ 0.00000000e+00, -4.58740940e-02, -1.12583334e-01,
        -1.95902278e-02, -4.65746037e-02, -3.36858172e-01,
        -1.83124688e-01, -9.95468292e-03, -9.53207205e-06,
        -1.09285190e-01,  3.23949005e-02,  1.58764021e-01,
         1.15786549e-01,  2.68086939e-01, -6.91990086e-02,
        -9.57739334e-03,  0.00000000e+00,  1.65684078e-02,
         1.42090886e-01,  1.27837579e-02, -3.53468964e-01,
         2.54663531e-01, -1.07367790e-01, -1.65921743e-03,
        -8.10294715e-07, -3.02201944e-03,  5.15353639e-03,
        -1.78565951e-01, -5.60929294e-01,  8.06923048e-02,
         4.07113618e-02, -8.81746055e-04,  0.00000000e+00,
         1.20396462e-01,  2.61287581e-01, -1.99564325e-01,
        -5.97030876e-01, -7.89206243e-02,  1.09557703e-01,
         0.00000000e+00, -2.92991264e-03, -7.35480579e-02,
         2.17064472e-01, -2.76149749e-01, -2.85848692e-01,
        -6.88685251e-02,  1.18378906e-01, -1.76444453e-04,
        -7.00733623e-03, -1.23975603e-01,  3.75907890e-0

In [14]:
reg.intercept_

array([-0.02086605, -2.22189539, -0.03796558, -0.17112187,  0.01263391,
       -0.08008812, -0.03477325, -0.0146118 , -2.14532697, -0.49808528])

In [15]:
pre = reg.predict(x_test)

## linear regression

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
a=LinearRegression()

In [18]:
a.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
pre2= a.predict(x_test)

## a.classification score

In [20]:
reg.score(x_test,y_test)

0.9574074074074074

## b.Logarthmic loss

In [21]:
from sklearn.model_selection import KFold

In [22]:
from sklearn import model_selection

In [24]:
kfold =model_selection.KFold(n_splits= 10,random_state=7)
result = model_selection.cross_val_score(reg,x,y,cv= kfold,scoring = "neg_log_loss")


C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [25]:
result

array([-0.45798961, -0.14435058, -0.61749705, -0.27323142, -0.27594697,
       -0.12815811, -0.11024468, -0.1233365 , -0.62592303, -0.68553964])

## c.r2 metrics

In [27]:
result2 = model_selection.cross_val_score(a,x,y,cv= kfold,scoring = "r2")

In [28]:
result2

array([0.40105499, 0.63102463, 0.57072313, 0.59629035, 0.54519634,
       0.67174215, 0.61763556, 0.47611004, 0.4236549 , 0.41044286])

## d. mean absolute error

In [29]:
from sklearn.metrics import mean_absolute_error

In [53]:
mean_absolute_error(y_test,pre2)

1.4688728777834479

## e.mean squared error

In [32]:
from sklearn.metrics import mean_squared_error

In [36]:
mean_squared_error(y_test,pre2)

3.491272304306336

## f.confusion matrics

In [40]:
from sklearn.metrics import confusion_matrix

In [55]:
print(confusion_matrix(y_test,pre))

[[51  0  0  0  0  0  0  0  0  0]
 [ 0 43  0  0  0  0  0  0  1  1]
 [ 0  0 50  1  0  0  0  0  0  1]
 [ 0  0  0 65  0  4  0  0  1  0]
 [ 0  0  0  0 48  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  0]
 [ 0  1  0  0  0  1 72  0  0  0]
 [ 0  0  0  0  0  0  0 51  1  0]
 [ 0  2  0  1  0  1  0  0 50  0]
 [ 0  0  0  1  0  0  0  2  4 48]]


## g.classification report

In [46]:
from sklearn.metrics import classification_report

In [51]:
print(classification_report(y_test,pre))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        51
          1       0.93      0.96      0.95        45
          2       1.00      0.96      0.98        52
          3       0.96      0.93      0.94        70
          4       1.00      1.00      1.00        48
          5       0.87      1.00      0.93        39
          6       1.00      0.97      0.99        74
          7       0.96      0.98      0.97        52
          8       0.88      0.93      0.90        54
          9       0.96      0.87      0.91        55

avg / total       0.96      0.96      0.96       540

