## question 1

In [4]:
 ## p(yes) y = 9/14 = 0.64 p(sunny) s= 5/14 = 0.357 p(sunny/yes) A = 3/9 = 0.33 p(yes/sunny) = (p(sunny/yes) *P(yes))/P(sunny)= 3/5

In [7]:
##yes = 9/14
##s= 5/14
##A = 3/9
##P = A*y/s##

In [10]:
#P=0.6

## question 2

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
from sklearn.datasets import load_iris
digit = load_iris()
x = digit.data
y=digit.target

In [15]:
x=pd.DataFrame(x)
y=pd.DataFrame(y)

In [16]:
x.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [17]:
y.head()

0
0  0
1  0
2  0
3  0
4  0

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [20]:
y_train.shape

(120, 1)

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
a = GaussianNB()

In [23]:
a.fit(x_train,y_train.values.reshape(120))

GaussianNB(priors=None)

In [24]:
pred = a.predict(x_test)

In [25]:
a.score(x_test,y_test)*100

100.0

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
print(confusion_matrix(y_test,pred))

[[ 9  0  0]
 [ 0  8  0]
 [ 0  0 13]]


In [28]:
from sklearn.metrics import classification_report

In [29]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       1.00      1.00      1.00         8
          2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        30



In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
b=MultinomialNB()

In [32]:
b.fit(x_train,y_train)

C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [33]:
pred2=b.predict(x_test)

In [34]:
b.score(x_test,y_test)*100

70.0

In [35]:
print(confusion_matrix(y_test,pred2))

[[9 0 0]
 [0 8 0]
 [0 9 4]]


In [36]:
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       0.47      1.00      0.64         8
          2       1.00      0.31      0.47        13

avg / total       0.86      0.70      0.67        30

