## question 1

In [2]:
import numpy as np

In [5]:
a=np.random.random(10).reshape(10,1)

In [6]:
a

array([[0.29799583],
       [0.91108767],
       [0.62611689],
       [0.03846293],
       [0.388061  ],
       [0.89251553],
       [0.69513949],
       [0.1587832 ],
       [0.24578929],
       [0.75802759]])

In [7]:
np.mean(a)

0.5011979421482644

## question 2

In [ ]:
b=np.random.random([20,1])

In [9]:
b

array([[0.67614451],
       [0.42971841],
       [0.39450658],
       [0.45600968],
       [0.37193065],
       [0.34914475],
       [0.96449648],
       [0.52829573],
       [0.60254939],
       [0.87971026],
       [0.94620153],
       [0.13618603],
       [0.84892737],
       [0.77872082],
       [0.64267115],
       [0.87392473],
       [0.95651302],
       [0.0247836 ],
       [0.37557068],
       [0.71187352]])

In [10]:
np.var(b)

0.07277031589200804

In [11]:
np.std(b)

0.26975973734419306

## question 3

In [19]:
c= np.random.random([10,20])

In [20]:
d= np.random.random([20,25])

In [21]:
e= np.dot(c,d)

In [ ]:
e

array([[5.22894763, 5.29409825, 4.91481804, 4.71960208, 4.98764657,
        5.88085223, 3.85843799, 5.10794882, 4.72280843, 3.90264429,
        3.92912211, 4.93591625, 5.51956537, 5.0658619 , 4.05308245,
        4.04311888, 5.2267389 , 4.90756748, 3.85076141, 5.58610625,
        4.17719284, 4.74190004, 4.7814704 , 3.80587238, 4.83300118],
       [4.86613118, 4.70331639, 4.31489639, 4.4532999 , 5.16339038,
        5.79212219, 3.55117376, 4.59085621, 3.71490543, 3.27289874,
        4.59730556, 5.24174393, 4.65463709, 3.64825604, 3.96246647,
        4.32634894, 5.52360616, 3.74789489, 3.80100913, 5.50527014,
        3.93572083, 4.22308727, 4.35652552, 4.07068785, 3.69426745],
       [5.45935153, 5.54274945, 4.45841389, 4.9407945 , 5.75461795,
        6.50249009, 4.69781231, 5.9928721 , 4.49681715, 4.45481736,
        6.07704437, 5.33766633, 6.48381675, 4.99281209, 4.66706186,
        5.26468006, 6.11533792, 4.58870404, 4.03235159, 6.16829447,
        4.57677052, 4.5291792 , 5.27381259, 4.

In [23]:
e.shape

(10L, 25L)

In [24]:
np.sum(e)

1212.5626204190235

## question 4

In [28]:
f = np.arange(10).reshape(10,1)

In [35]:
def myfunc(x,axis):
    return 1/(1+np.exp(-x))

In [36]:
 np.apply_over_axes(myfunc,f,1)

array([[0.5       ],
       [0.73105858],
       [0.88079708],
       [0.95257413],
       [0.98201379],
       [0.99330715],
       [0.99752738],
       [0.99908895],
       [0.99966465],
       [0.99987661]])