In [109]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = pd.read_csv("C:/Users/pawan/train.csv",header=None)

In [5]:
a

0                      1  \
0      0   '591764470197723137'   
1      0   '591779538046218240'   
2      0   '591728244925210624'   
3      0   '591774433926193152'   
4      0   '591764472651386882'   
5      0   '591751543025569793'   
6      0   '591727216267890688'   
7      0   '591739000001470464'   
8      0   '591753691084038146'   
9      0   '591747428358881282'   
10     0   '591760691872169985'   
11     0   '591770916360560640'   
12     0   '591751403221098496'   
13     0   '591726847219478528'   
14     0   '591714830446301184'   
15     0   '591732037159030785'   
16     0   '591672103788621824'   
17     0   '591673483832270848'   
18     0   '591729367132188672'   
19     0   '591746927269523458'   
20     0   '591729090832437248'   
21     0   '591752371241267200'   
22     0   '591747039844667392'   
23     0   '591741541514772480'   
24     0   '591742811784884225'   
25     0   '591744262917660674'   
26     0   '591773192907202560'   
27     0   '591744687058198528'   
28     0   '591737214868021248'   
29     0   '591747765916413952'   
...   ..                    ...   
18056  2   '592642423265894401'   
18057  2   '592643848385335296'   
18058  2   '592645149282340864'   
18059  2   '592643776625123328'   
18060  2   '592648262315876353'   
18061  2   '592648593384738816'   
18062  2   '592651886215430144'   
18063  2   '592652635439697921'   
18064  2   '592652513360220160'   
18065  2   '592660156183371776'   
18066  2   '592661430979141633'   
18067  2   '592663760919232512'   
18068  2   '592666086690189313'   
18069  2   '592667760880132096'   
18070  2   '592670897477165059'   
18071  2   '592674856279355393'   
18072  2   '592677666144288769'   
18073  2   '592677515514269696'   
18074  2   '592679798817816576'   
18075  2   '592682158814339072'   
18076  2   '592684009563549696'   
18077  2   '592683279188361217'   
18078  2   '592694344655699968'   
18079  2   '592697492422144000'   
18080  2   '592696857815572481'   
18081  2   '592697535271174145'   
18082  2   '592697135390416899'   
18083  2   '592698989507715075'   
18084  1     '5644654646545646'   
18085  2      '543533654345435'   

                                                       2  \
0       '#Nepal #news Adding to Bhutanese Refugees Bh...   
1       "The massacre of people's movement says peace...   
2                                            "I'm lonely   
3       '#nepal #news 6 billion collection collection...   
4       '#Nepal #news Indian proposal to crash airpor...   
5       'God also ran away for money after the poor l...   
6                    'Someone feels like a tile to see'    
7       'The boys began to write English passage. I -...   
8                                    "I will not go away   
9                                          'Gaurab Sir'    
10                           'Nepal is shaken as a cheat   
11      'Baba Ramdev to clean Bagramati Ray in Kiripu...   
12      'Seventh Asian Asian Games Madras Bastasta wo...   
13      "See What's New Updates Get Started in the So...   
14      'original one by Anjum Rahbar I used to flame...   
15                                     "Let's compromise   
16      'Gajendra received a diary. Extremely Beautif...   
17      "Nepal's Autism Children cooperate in Korea N...   
18                                       'Good morning'    
19                                             'Sheikh'    
20      'The photo should not be sent when you are si...   
21                       'You are the queen of my castle   
22                                             'Hunter'    
23                                'Can you be a friend'    
24                             'If I am to wrap with you   
25      'Just ask the right to ask all of these Tweet...   
26              'Good day all the friends of Jai Nepal'    
27                          'There is a lot of sulfony'    
28      'General Knowledge Get all quiz in Nepali lan...   
29      'All of these floors are cur

In [6]:
a = a.fillna(value=" ")

In [7]:
a["texts"] = a[2].map(str)+a[3].map(str)+a[4].map(str)+a[5].map(str)+a[6].map(str)+a[7].map(str)+a[8].map(str)

In [9]:
a

0                      1  \
0      0   '591764470197723137'   
1      0   '591779538046218240'   
2      0   '591728244925210624'   
3      0   '591774433926193152'   
4      0   '591764472651386882'   
5      0   '591751543025569793'   
6      0   '591727216267890688'   
7      0   '591739000001470464'   
8      0   '591753691084038146'   
9      0   '591747428358881282'   
10     0   '591760691872169985'   
11     0   '591770916360560640'   
12     0   '591751403221098496'   
13     0   '591726847219478528'   
14     0   '591714830446301184'   
15     0   '591732037159030785'   
16     0   '591672103788621824'   
17     0   '591673483832270848'   
18     0   '591729367132188672'   
19     0   '591746927269523458'   
20     0   '591729090832437248'   
21     0   '591752371241267200'   
22     0   '591747039844667392'   
23     0   '591741541514772480'   
24     0   '591742811784884225'   
25     0   '591744262917660674'   
26     0   '591773192907202560'   
27     0   '591744687058198528'   
28     0   '591737214868021248'   
29     0   '591747765916413952'   
...   ..                    ...   
18056  2   '592642423265894401'   
18057  2   '592643848385335296'   
18058  2   '592645149282340864'   
18059  2   '592643776625123328'   
18060  2   '592648262315876353'   
18061  2   '592648593384738816'   
18062  2   '592651886215430144'   
18063  2   '592652635439697921'   
18064  2   '592652513360220160'   
18065  2   '592660156183371776'   
18066  2   '592661430979141633'   
18067  2   '592663760919232512'   
18068  2   '592666086690189313'   
18069  2   '592667760880132096'   
18070  2   '592670897477165059'   
18071  2   '592674856279355393'   
18072  2   '592677666144288769'   
18073  2   '592677515514269696'   
18074  2   '592679798817816576'   
18075  2   '592682158814339072'   
18076  2   '592684009563549696'   
18077  2   '592683279188361217'   
18078  2   '592694344655699968'   
18079  2   '592697492422144000'   
18080  2   '592696857815572481'   
18081  2   '592697535271174145'   
18082  2   '592697135390416899'   
18083  2   '592698989507715075'   
18084  1     '5644654646545646'   
18085  2      '543533654345435'   

                                                       2  \
0       '#Nepal #news Adding to Bhutanese Refugees Bh...   
1       "The massacre of people's movement says peace...   
2                                            "I'm lonely   
3       '#nepal #news 6 billion collection collection...   
4       '#Nepal #news Indian proposal to crash airpor...   
5       'God also ran away for money after the poor l...   
6                    'Someone feels like a tile to see'    
7       'The boys began to write English passage. I -...   
8                                    "I will not go away   
9                                          'Gaurab Sir'    
10                           'Nepal is shaken as a cheat   
11      'Baba Ramdev to clean Bagramati Ray in Kiripu...   
12      'Seventh Asian Asian Games Madras Bastasta wo...   
13      "See What's New Updates Get Started in the So...   
14      'original one by Anjum Rahbar I used to flame...   
15                                     "Let's compromise   
16      'Gajendra received a diary. Extremely Beautif...   
17      "Nepal's Autism Children cooperate in Korea N...   
18                                       'Good morning'    
19                                             'Sheikh'    
20      'The photo should not be sent when you are si...   
21                       'You are the queen of my castle   
22                                             'Hunter'    
23                                'Can you be a friend'    
24                             'If I am to wrap with you   
25      'Just ask the right to ask all of these Tweet...   
26              'Good day all the friends of Jai Nepal'    
27                          'There is a lot of sulfony'    
28      'General Knowledge Get all quiz in Nepali lan...   
29      'All of these floors are cur

In [10]:
a = a.drop(columns=[2,3,4,5,6,7,8],axis = 1)

In [11]:
a.shape

(18086, 3)

In [12]:
a["texts"][0]

" '#Nepal #news Adding to Bhutanese Refugees Bhutanese citizens of Nepalese origin still refrain from leaving their bags.'       "

In [13]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stopword = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pawan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [68]:
a['texts'] = a['texts'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopword)]))

In [69]:
from sklearn.feature_extraction import text

In [70]:
b = text.TfidfVectorizer()

In [71]:
x = b.fit_transform(a["texts"])

In [73]:
x.shape

(18086, 17081)

In [74]:
b.vocabulary_

{'nepal': 10091,
 'news': 10203,
 'adding': 823,
 'bhutanese': 2242,
 'refugees': 12246,
 'citizens': 3127,
 'nepalese': 10127,
 'origin': 10643,
 'still': 14138,
 'refrain': 12240,
 'leaving': 8618,
 'bags': 1782,
 'the': 14864,
 'massacre': 9202,
 'people': 11055,
 'movement': 9702,
 'says': 13079,
 'peace': 11023,
 'constitution': 3480,
 'lost': 8860,
 'country': 3633,
 'lonely': 8831,
 'maybe': 9252,
 'going': 6252,
 'die': 4337,
 'without': 16342,
 'closing': 3187,
 'city': 3128,
 'love': 8872,
 'leave': 8616,
 'billion': 2281,
 'collection': 3250,
 '12': 55,
 'one': 10536,
 'year': 16589,
 'half': 6528,
 '30': 225,
 'thousand': 14945,
 'foreign': 5810,
 'studies': 14233,
 'indian': 7332,
 'proposal': 11712,
 'crash': 3675,
 'airport': 1023,
 'crashes': 3677,
 'four': 5857,
 'days': 3921,
 'god': 6231,
 'also': 1113,
 'ran': 12035,
 'away': 1688,
 'money': 9607,
 'poor': 11358,
 'listened': 8746,
 'asked': 1515,
 'for': 5793,
 'someone': 13875,
 'feels': 5581,
 'like': 8706,
 'til

In [75]:
a

0                      1  \
0      0   '591764470197723137'   
1      0   '591779538046218240'   
2      0   '591728244925210624'   
3      0   '591774433926193152'   
4      0   '591764472651386882'   
5      0   '591751543025569793'   
6      0   '591727216267890688'   
7      0   '591739000001470464'   
8      0   '591753691084038146'   
9      0   '591747428358881282'   
10     0   '591760691872169985'   
11     0   '591770916360560640'   
12     0   '591751403221098496'   
13     0   '591726847219478528'   
14     0   '591714830446301184'   
15     0   '591732037159030785'   
16     0   '591672103788621824'   
17     0   '591673483832270848'   
18     0   '591729367132188672'   
19     0   '591746927269523458'   
20     0   '591729090832437248'   
21     0   '591752371241267200'   
22     0   '591747039844667392'   
23     0   '591741541514772480'   
24     0   '591742811784884225'   
25     0   '591744262917660674'   
26     0   '591773192907202560'   
27     0   '591744687058198528'   
28     0   '591737214868021248'   
29     0   '591747765916413952'   
...   ..                    ...   
18056  2   '592642423265894401'   
18057  2   '592643848385335296'   
18058  2   '592645149282340864'   
18059  2   '592643776625123328'   
18060  2   '592648262315876353'   
18061  2   '592648593384738816'   
18062  2   '592651886215430144'   
18063  2   '592652635439697921'   
18064  2   '592652513360220160'   
18065  2   '592660156183371776'   
18066  2   '592661430979141633'   
18067  2   '592663760919232512'   
18068  2   '592666086690189313'   
18069  2   '592667760880132096'   
18070  2   '592670897477165059'   
18071  2   '592674856279355393'   
18072  2   '592677666144288769'   
18073  2   '592677515514269696'   
18074  2   '592679798817816576'   
18075  2   '592682158814339072'   
18076  2   '592684009563549696'   
18077  2   '592683279188361217'   
18078  2   '592694344655699968'   
18079  2   '592697492422144000'   
18080  2   '592696857815572481'   
18081  2   '592697535271174145'   
18082  2   '592697135390416899'   
18083  2   '592698989507715075'   
18084  1     '5644654646545646'   
18085  2      '543533654345435'   

                                                   texts  
0      '#Nepal #news Adding Bhutanese Refugees Bhutan...  
1      "The massacre people's movement says peace con...  
2      "I'm lonely maybe going die without closing ci...  
3      '#nepal #news 6 billion collection collection ...  
4      '#Nepal #news Indian proposal crash airport cr...  
5      'God also ran away money poor listened asked for'  
6                          'Someone feels like tile see'  
7        'The boys began write English passage. I - taw'  
8             "I go away going broken I'm going get you"  
9                                           'Gaurab Sir'  
10                   'Nepal shaken cheat cheats give us'  
11     'Baba Ramdev clean Bagramati Ray Kiripur. Now ...  
12     'Seventh Asian Asian Games Madras Bastasta tit...  
13     "See What's New Updates Get Started Society Sa...  
14     'original one Anjum Rahbar I used flame flames...  
15     "Let's compromise I steal temper miss memories...  
16     'Gajendra received diary. Extremely Beautiful ...  
17     "Nepal's Autism Children cooperate Korea Nepal...  
18                                        'Good morning'  
19                                              'Sheikh'  
20                          'The photo sent sitting Dil'  
21     'You queen castle queen mine. We heavens. I ha...  
22                                              'Hunter'  
23                                          'Can friend'  
24           'If I wrap I learn write books literature.'  
25               'Just ask right ask Tweets copyrighted'  
26                          'Good day friends Jai Nepal'  
27                                   'There lot sulfony'  
28     'General Knowledge Get quiz Nepali language lo...  
29              'All floors currently active .Thank you'  
...    

In [76]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [77]:
d= pd.DataFrame(a[0])

In [80]:
a2 = SelectKBest(chi2,k=4).fit_transform(x,d)

In [81]:
a2.shape

(18086, 4)

In [82]:
from sklearn.model_selection import StratifiedShuffleSplit

In [83]:
shuffle = StratifiedShuffleSplit(n_splits=101,random_state=7)

In [84]:
d= d.values.reshape(18086)

In [85]:
for train_index, test_index in shuffle.split(a2, d):
    x_train, x_test = a2[train_index], a2[test_index]
    d_train, d_test = d[train_index], d[test_index]

## gaussianNB

In [86]:
from sklearn.naive_bayes import GaussianNB

In [87]:
g = GaussianNB()

In [88]:
g.fit(x_train.todense(),d_train)

GaussianNB(priors=None)

In [89]:
g2 =  g.predict(x_test.todense())

In [90]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

In [92]:
accuracy_score(g2,d_test)

0.9574350469872858

In [93]:
print(classification_report(g2,d_test))

             precision    recall  f1-score   support

          0       0.98      0.98      0.98      1706
          1       0.50      0.34      0.41        29
          2       0.64      0.57      0.60        74

avg / total       0.95      0.96      0.96      1809



In [94]:
print(confusion_matrix(g2,d_test))

[[1680    8   18]
 [  13   10    6]
 [  30    2   42]]


In [193]:
f1_g = f1_score(g2,d_test,average='weighted')
print(f1_g)

0.9551728998417566


## multinomial NB

In [96]:
from sklearn.naive_bayes import MultinomialNB

In [98]:
m = MultinomialNB()
m.fit(x_train,d_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [100]:
m2 = m.predict(x_test)

In [101]:
print(accuracy_score(m2,d_test)*100)

95.24599226091763


In [102]:
print(classification_report(m2,d_test))

             precision    recall  f1-score   support

          0       1.00      0.95      0.98      1809
          1       0.00      0.00      0.00         0
          2       0.00      0.00      0.00         0

avg / total       1.00      0.95      0.98      1809



C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [103]:
print(confusion_matrix(m2,d_test))

[[1723   20   66]
 [   0    0    0]
 [   0    0    0]]


In [113]:
from sklearn.metrics import f1_score

In [115]:
f1_multi = f1_score(m2,d_test,average='weighted')
print(f1_multi)

0.9756511891279728


C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


## svm

In [116]:
from sklearn.svm import SVC

In [117]:
linear_svc = SVC(kernel = "linear")

In [118]:
linear_svc.fit(x_train,d_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [119]:
linear_SVC2 =linear_svc.predict(x_test)

In [120]:
print(accuracy_score(linear_SVC2,d_test))

0.9596462133775566


In [123]:
print(classification_report(linear_SVC2,d_test))

             precision    recall  f1-score   support

          0       1.00      0.96      0.98      1790
          1       0.00      0.00      0.00         0
          2       0.24      0.84      0.38        19

avg / total       0.99      0.96      0.97      1809



C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [125]:
print(confusion_matrix(linear_SVC2,d_test))

[[1720   20   50]
 [   0    0    0]
 [   3    0   16]]


In [127]:
f1_linear_SVC2 = f1_score(linear_SVC2,d_test,average='weighted')
print(f1_linear_SVC2)

0.9728893380384257


C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [128]:
poly_SVC  = SVC(kernel="poly",degree=8)

In [129]:
poly_SVC.fit(x_train,d_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [130]:
poly_SVC2=poly_SVC.predict(x_test)

In [131]:
print(accuracy_score(poly_SVC2,d_test)*100)

95.24599226091763


In [132]:
print(classification_report(poly_SVC2,d_test))

             precision    recall  f1-score   support

          0       1.00      0.95      0.98      1809
          1       0.00      0.00      0.00         0
          2       0.00      0.00      0.00         0

avg / total       1.00      0.95      0.98      1809



C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [133]:
print(confusion_matrix(poly_SVC2,d_test))

[[1723   20   66]
 [   0    0    0]
 [   0    0    0]]


In [134]:
f1_poly_SVC2 = f1_score(poly_SVC2,d_test,average='weighted')
print(f1_poly_SVC2)

0.9756511891279728


C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [135]:
gaussion_SVC = SVC(kernel="rbf")

In [136]:
gaussion_SVC.fit(x_train,d_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [139]:
gaussion_SVC2= gaussion_SVC.predict(x_test)

In [140]:
print(classification_report(gaussion_SVC2,d_test))

             precision    recall  f1-score   support

          0       1.00      0.96      0.98      1789
          1       0.00      0.00      0.00         0
          2       0.26      0.85      0.40        20

avg / total       0.99      0.96      0.97      1809



C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [141]:
print(accuracy_score(gaussion_SVC2,d_test)*100)

96.01990049751244


In [142]:
f1_gaussion_SVC2 = f1_score(gaussion_SVC2,d_test,average='weighted')
print(f1_gaussion_SVC2)

0.9730405965498975


C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [143]:
def check(strg):
    a=[]
    from nltk.tokenize import word_tokenize
    nltk.download("punkt")
    word_tokens = word_tokenize(strg)
    
    for w in word_tokens:
        if w not in stopword:
                a.append(w)
    vec = text.TfidfVectorizer()
    st =  vec.fit_transform(a)
    return st


In [157]:
strn = "I m lonely"

In [158]:
z = check(strn)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\pawan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [159]:
g.predict(z.todense())

array([0, 2], dtype=int64)

## decision tree

In [161]:
from sklearn.tree import DecisionTreeClassifier

In [162]:
dt=DecisionTreeClassifier()

In [163]:
dt.fit(x_train,d_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [164]:
dt2 = dt.predict(X_test)

In [165]:
print(classification_report(dt2,d_test))

             precision    recall  f1-score   support

          0       0.99      0.98      0.98      1742
          1       0.30      0.35      0.32        17
          2       0.48      0.64      0.55        50

avg / total       0.97      0.96      0.96      1809



In [166]:
print(confusion_matrix(dt2,d_test))

[[1701   12   29]
 [   6    6    5]
 [  16    2   32]]


In [167]:
print(accuracy_score(dt2,d_test))

0.9613045881702598


In [168]:
f1_dt = f1_score(dt2,d_test,average="weighted")
print(f1_dt)

0.9637517927790701


## random forest

In [169]:
from sklearn.ensemble import RandomForestClassifier

In [170]:
rt = RandomForestClassifier(n_estimators=10,n_jobs=2,random_state=7)

In [171]:
rt.fit(x_train,d_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=7, verbose=0, warm_start=False)

In [172]:
rt2 = rt.predict(x_test)

In [173]:
print(classification_report(rt2,d_test))

             precision    recall  f1-score   support

          0       0.99      0.97      0.98      1750
          1       0.25      0.33      0.29        15
          2       0.45      0.68      0.55        44

avg / total       0.97      0.96      0.97      1809



In [174]:
print(confusion_matrix(rt2,d_test))

[[1705   14   31]
 [   5    5    5]
 [  13    1   30]]


In [176]:
print(accuracy_score(rt2,d_test))

0.9618573797678275


In [177]:
f1_rt = f1_score(rt2,d_test,average="weighted")
print(f1_rt)

0.9654730929468672


## vooting classifier

In [178]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [179]:
estimater = []
model4 = LogisticRegression()
estimater.append(("Logistic",model4))
model5 = KMeans()
estimater.append(("KMeans",model5))
model6 = SVC(kernel="rbf")
estimater.append(("SVC",model6))
model7 = GaussianNB()
estimater.append(("Gaussian",model7))
model8 =  KNeighborsClassifier()
estimater.append(("KNN",model8))

In [180]:
Vot = VotingClassifier(estimater)

In [181]:
Vot.fit(x_train.todense(),d_train)

VotingClassifier(estimators=[('Logistic', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('KMeans...owski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [182]:
Vot2 = Vot.predict(x_test.todense())

C:\Users\pawan\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [183]:
print(classification_report(Vot2,d_test))

             precision    recall  f1-score   support

          0       1.00      0.97      0.98      1775
          1       0.10      0.67      0.17         3
          2       0.39      0.84      0.54        31

avg / total       0.98      0.96      0.97      1809



In [184]:
print(confusion_matrix(Vot2,d_test))

[[1717   18   40]
 [   1    2    0]
 [   5    0   26]]


In [185]:
print(accuracy_score(Vot2,d_test))

0.9646213377556662


In [187]:
f1_vot2=f1_score(Vot2,d_test,average="weighted")
print(f1_vot2)

0.9727278028917838


In [194]:
app_algo = ["Gassuian Naive Bayes","Multinomial Naive Bayes","Linear SVC","Polynomial_SVC","Gassuian SVC","Decision Tree","Random Forest","Voting"]
F1_res = [f1_g,f1_multi,f1_linear_SVC2,f1_poly_SVC2,f1_gaussion_SVC2,f1_dt,f1_rt,f1_vot2]

In [195]:
results = pd.DataFrame({"Algo":app_algo,"F1 score":F1_res},index=[1,2,3,4,5,6,7,8])

In [196]:
results

Algo  F1 score
1     Gassuian Naive Bayes  0.955173
2  Multinomial Naive Bayes  0.975651
3               Linear SVC  0.972889
4           Polynomial_SVC  0.975651
5             Gassuian SVC  0.973041
6            Decision Tree  0.963752
7            Random Forest  0.965473
8                   Voting  0.972728